-- Migration: Step 3 Reporting and Advanced Analytics
-- Date: 2026-03-07

-- 1. Add plan_type to groups
ALTER TABLE public.groups
ADD COLUMN IF NOT EXISTS plan_type TEXT DEFAULT 'free' CHECK (plan_type IN ('free', 'pro', 'institution_50'));

-- 2. Update diagnosis_records to support projects and pre/post types
ALTER TABLE public.diagnosis_records
ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES public.projects(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS diag_type TEXT DEFAULT 'standard' CHECK (diag_type IN ('standard', 'pre', 'post'));

-- 3. Create consultations table (Professional matching & advanced mentoring)
-- Extends the concept of mentoring_memos for more formal expert matching
CREATE TABLE IF NOT EXISTS public.consultations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  company_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  expert_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'matched', 'in_progress', 'completed', 'cancelled')),
  summary TEXT, -- Expert's summary for AI reporting
  feedback TEXT, -- Direct feedback to company
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create reports table for AI-generated project insights
CREATE TABLE IF NOT EXISTS public.reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  ai_insight TEXT, -- The core analytical text generated by LLM
  stats_cache JSONB, -- Snapshotted statistics used for the report
  pdf_url TEXT,
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Enable RLS and add policies
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Consultations Policies
CREATE POLICY "Super admins can manage all consultations" ON public.consultations
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin')
  );

CREATE POLICY "Group admins can manage group consultations" ON public.consultations
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      JOIN public.projects proj ON proj.id = public.consultations.project_id
      WHERE p.id = auth.uid() AND p.role = 'group_admin' AND p.group_id = proj.group_id
    )
  );

CREATE POLICY "Experts can view/update assigned consultations" ON public.consultations
  FOR ALL USING (auth.uid() = expert_id);

CREATE POLICY "Companies can view their own consultations" ON public.consultations
  FOR SELECT USING (auth.uid() = company_id);

-- Reports Policies
CREATE POLICY "Super admins can manage all reports" ON public.reports
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin')
  );

CREATE POLICY "Group admins can manage group reports" ON public.reports
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      JOIN public.projects proj ON proj.id = public.reports.project_id
      WHERE p.id = auth.uid() AND p.role = 'group_admin' AND p.group_id = proj.group_id
    )
  );
